configfile: "config/config.yaml"

rule all:
    input:
        expand("results/n_nodes={n_nodes}/{file}.png", n_nodes=[1, 10], file={"energy","schedule"})

rule test_chain:
    output:
        report(
            "results/{n_nodes}/energy.png", 
            category="Chains",
            subcategory="Energies",
            labels={
                "n_nodes" : "{n_nodes}"
            }
        ),
        report(
            "results/{n_nodes}/schedule.png", 
            category="Chains",
            subcategory="Schedules",
            labels={
                "n_nodes" : "{n_nodes}"
            }
        ),
        "results/n_nodes={n_nodes}/best_graph.adjlist"
    threads: 6
    shell:
        "mpiexec -n {threads} python ../src/pt/parallel_tempering.py {output[0]} {output[1]} {output[2]}"